# keep time in sync
---
  
- name: install some base packages (Debian) 
  apt:  pkg={{ item }} state=latest
  with_items:
      - ntp 
      - facter
  when: ansible_os_family == "Debian"
  tags:
   - ntp

- name: install ntp daemon and use clock prefs (RedHat)
  yum:  pkg={{ item }} state=latest
  with_items:
      - ntp 
      - facter
  when: ansible_os_family == "RedHat"
  tags:
   - ntp

- name: start ntp daemon 
  service: name={{ ntp }} state=running enabled=yes
  tags:
   - ntp

- name: send new config and restart service
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
  tags:
   - ntp

- name: set correct timezone
  file: src=/usr/share/zoneinfo/Europe/London dest=/etc/localtime state=link owner=root group=root force=yes
  tags:
   - ntp


- include: sudo.yml
- include: user.yml
