# manage users and their home dirs
---
  
- name: manage users 
  user: name={{ item }} state=present createhome=yes home=/home/{{ item }} shell=/bin/bash
  with_items:
     - user1
     - user2
     - user3
     - user4

- name: creating .ssh directory for 
  file: dest=/home/{{ item }}/.ssh mode=700 owner={{ item }}  group={{ item }} state=present
  with_items:
     - user1
     - user2
     - user3
     - user4 
