# manage apache install and configuration
---
  
- name: install apache 
  apt:  pkg={{ apache }} state=installed

- name: install apache (RedHat)
  yum:  pkg={{ apache }} state=installed
  when: ansible_os_family == "RedHat"

- name: start apache and enable on startup
  service: name={{ apache }} state=running enabled=yes

- name: sync config file 
  template: src={{ httpconf }}.conf.j2 dest=/etc/{{ httpconf }}/{{httpconf}}.conf
  notify: restart apache
